apiVersion: v1
kind: Service
metadata:
  name: dagster-webserver
  namespace: dagster
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: dagster
    component: dagster-webserver
  ports:
    - port: 80
      targetPort: 80
